namespace AIAgents.Core.Models;

/// <summary>
/// Represents a test case generated by the testing agent.
/// </summary>
public sealed record TestCase
{
    public required string Name { get; init; }
    public required string Type { get; init; }
    public required string Priority { get; init; }
    public required string Description { get; init; }
    public required string ExpectedResult { get; init; }
}
